spring:
  application:
    name: lab3-inf-sys-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/studs
    username: s368530
    password: P7Woe7Cwyk2MjZnN
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: app-hikari
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: false
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        javax:
          cache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider
            uri: classpath:ehcache.xml
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: true

  thymeleaf:
    check-template-location: false

  sql:
    init:
      mode: always
      encoding: UTF-8

  jackson:
    serialization:
      write-dates-as-timestamps: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: eternal.martyr13579@gmail.com
    password: "zyza pyuz jjad tmjn"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

app:
  cache:
    l2:
      stats:
        enabled: true
  websocket:
    allowed-origins: "*"

  password-reset:
    frontend-reset-url-template: "http://localhost:5173/reset-password?token=%s"
    token-ttl-minutes: 15
    from-email: "eternal.martyr13579@gmail.com"

  minio:
    endpoint: "http://localhost:9000"
    access-key: "minioadmin"
    secret-key: "minioadmin"
    bucket: "imports"
    create-bucket: true

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
